apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitio-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitio-web
  template:
    metadata:
      labels:
        app: sitio-web
    spec:
      containers:
      - name: sitio-web
        image: nginx:latest
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: web-content-pvc

