apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitio-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitio-web
  template:
    metadata:
      labels:
        app: sitio-web
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 101:101 /usr/share/nginx/html && chmod -R 755 /usr/share/nginx/html"]
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      containers:
      - name: sitio-web
        image: nginx
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        persistentVolumeClaim:
          claimName: web-content-pvc

