apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-content-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/projects/static-website-content/html
